### PR TITLE
Import DVV rakennukset

### LINKED ISSUE #5: Fix db migration CI
Currently automatic migration tests are broken

### PR DESCRIPTION
**Pull request by Rikuoja**
Fix #5 . Address part of https://github.com/GispoCoding/jkr-lahti/issues/12 .

Leaving rakennuksen omistajat/vanhimmat to next sprint, along with https://github.com/GispoCoding/jkr-core/issues/3

### CODE REVIEW

File: scripts/import_dvv.sql [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    to_date("käytössä_olotilanteen muutospäivä"::text, 'YYYYMMDD') as kayttoonotto_pvm,
+    "käyttö_tarkoitus" as rakennuksenkayttotarkoitus_koodi,
+    "käytös_säolo_tilanne" as rakennuksenolotila_koodi
+from jkr_dvv.rakennus
+on conflict do nothing
+;
+
+-- Insert streets to jkr_osoite.katu
+-- jkr_osoite.kunta must be filled in the database by running import_posti.sql first!
+insert into jkr_osoite.katu (katunimi_fi, katunimi_sv, kunta_koodi)
```
Comment (LKajan) [inline scripts/import_dvv.sql:17]: In performance wise this query could be optimized slightly. Now this tries to do over 90 000 inserts and most of the time the street is already in the database.
We could prefilter only unique streets with:
```sql
select distinct
    "kadunnimi suomeksi" as katunimi_fi,
    "kadunnimi ruotsiksi" as katunimi_sv,
    sijainti_kunta as kunta_koodi
from jkr_dvv.osoite
```

File: scripts/import_dvv.sql [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+select
+    "kadunnimi suomeksi" as katunimi_fi,
+    "kadunnimi ruotsiksi" as katunimi_sv,
+    sijainti_kunta as kunta_koodi
+from jkr_dvv.osoite
+where osoite_numero is not null  -- not all places have street address
```
Comment (LKajan) [inline scripts/import_dvv.sql:23]: I would filter with `"kadunnimi suomeksi" is not null or "kadunnimi ruotsiksi" is not null`

File: scripts/import_dvv.sql [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+-- Assume Finnish kadunnimi is given. Some (two) entries might have errors because of this.
+insert into jkr.osoite (osoitenumero, katu_id, rakennus_id, posti_numero)
+select
+    katu_numero as osoitenumero,
+    (select id from jkr_osoite.katu where osoite."kadunnimi suomeksi" = katu.katunimi_fi and osoite.sijainti_kunta = katu.kunta_koodi) as katu_id,
+    (select id from jkr.rakennus where osoite.rakennustunnus = rakennus.prt) as rakennus_id,
+    posti_numero as posti_numero
+from jkr_dvv.osoite
+where
+    (select id from jkr.rakennus where osoite.rakennustunnus = rakennus.prt) is not null -- not all addresses have buildings
```
Comment (LKajan) [inline scripts/import_dvv.sql:36]: More efficient (probably) and widely used test for existence in another table would be
```sql
where
  exists (select 1 from jkr.rakennus r where osoite.rakennustunnus = r.prt)
  ...
```

File: scripts/import_katu.sql [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+INSERT INTO tmp_posti_baf_formatted(kuntakoodi, katunimi_fi, katunimi_sv)
+SELECT
+    substring(data, 214, 3) kuntakoodi,
+    nullif(trim(substring(data, 103, 30)), '') katunimi_fi,
+    nullif(trim(substring(data, 133, 30)), '') katunimi_sv
+FROM tmp_posti_baf
+;
+
+insert into jkr_osoite.katu(kunta_koodi, katunimi_fi, katunimi_sv)
```
Comment (LKajan) [inline scripts/import_katu.sql:23]: I think there is no need to import street names from other than the dvv data. Is this file unnecessary then?

**Review by LKajan — CHANGES_REQUESTED** [review]
Looks good!
Few performace optimizations and one critical issue.
Please fix at least the `kayttoonotto_pvm` value.

File: scripts/import_dvv.sql (hunk 1 above)
Comment (Rikuoja) [reply scripts/import_dvv.sql:17]: Certainly the queries could be improved, but if the query is run once a year and it takes a few seconds, how much is it worth to spend time optimizing such a query?

File: scripts/import_katu.sql (hunk 4 above)
Comment (Rikuoja) [reply scripts/import_katu.sql:23]: It might be unnecessary. I included it here and in the script file comments because the DVV streets names *might* contain too many errors, so it makes sense in my opinion to have a fallback script in the core to import the original error-free data from posti. We don't know yet if it is needed in the Lahti case, though.

File: scripts/import_dvv.sql [hunk 5]
```diff
@@ -0,0 +1,38 @@
+-- Insert buildings to jkr_rakennus
+insert into jkr.rakennus (prt, kiinteistotunnus, onko_viemari, geom, kayttoonotto_pvm, rakennuksenkayttotarkoitus_koodi, rakennuksenolotila_koodi)
+select 
+    rakennustunnus as prt,
+    "sijaintikiinteistön tunnus" as kiinteistotunnus,
+    viemäri::boolean as onko_viemari,
+    ST_GeomFromText('POINT('||itä_koordinaatti||' '||pohjois_koordinaatti||')', 3067) as geom,
+    to_date("käytössä_olotilanteen muutospäivä"::text, 'YYYYMMDD') as kayttoonotto_pvm,
```
[the remark this answers is not in the document]
Comment (Rikuoja) [reply scripts/import_dvv.sql]: Fixed. This caused the ugliest sql I've ever written tho, because
1) the name of the field, for some unfathomable reason, is "valmis_tumis_
_päivä" including the newline, and
2) the field contains errors which require checking the string before converting it to date.

**Review by LKajan — APPROVED** [review]
